apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.2.0
    replicas: 3
    listeners:
      - name: tls
        port: 9092
        type: ingress
        tls: true
        authentication:
          type: tls
        configuration: 
          bootstrap:
            host: bootstrap.mykafka.com
          brokers:
          - broker: 0
            host: broker-0.mykafka.com
          - broker: 1
            host: broker-1.mykafka.com
          - broker: 2
            host: broker-2.mykafka.com
    authorization:
      type: simple
      superUsers:
        - CN=user-admin
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
