apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: user-admin
spec:
  authentication:
    type: tls
  authorization:
    acls: []
    type: simple